Databases:
  DebateIndonesian: ./audio/{uri}.wav

Protocols:
  DebateIndonesian:
    SpeakerDiarization:
      Default:
        train:
          uri: ./lists/train.meetings.txt
          annotation: ./rttms/train/{uri}.rttm
          annotated: ./uems/train/{uri}.uem
        development:
          uri: ./lists/dev.meetings.txt
          annotation: ./rttms/dev/{uri}.rttm
          annotated: ./uems/dev/{uri}.uem
        test:
          uri: ./lists/test.meetings.txt
          annotation: ./rttms/test/{uri}.rttm
          annotated: ./uems/test/{uri}.uem
