Databases:
  DebateIndonesianLarge: dataset_debate_large\audio/{uri}.wav

Protocols:
  DebateIndonesianLarge:
    SpeakerDiarization:
      Default:
        train:
            uri: dataset_debate_large\lists/train.meetings.txt
            annotation: dataset_debate_large\rttms/train/{uri}.rttm
            annotated: dataset_debate_large\uems/train/{uri}.uem
        development:
            uri: dataset_debate_large\lists/dev.meetings.txt
            annotation: dataset_debate_large\rttms/dev/{uri}.rttm
            annotated: dataset_debate_large\uems/dev/{uri}.uem
        test:
            uri: dataset_debate_large\lists/test.meetings.txt
            annotation: dataset_debate_large\rttms/test/{uri}.rttm
            annotated: dataset_debate_large\uems/test/{uri}.uem
